apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-iam-authenticator-kubeconfig
  namespace: kube-system
data:
  kubeconfig: |
    # clusters refers to the remote service.
    clusters:
      - name: aws-iam-authenticator
        cluster:
          certificate-authority-data: ${iam_authenticator_cert}
          server: https://localhost:21362/authenticate
    # users refers to the API Server's webhook configuration
    # (we don't need to authenticate the API server).
    users:
      - name: apiserver
    # kubeconfig files require a context. Provide one for the API Server.
    current-context: webhook
    contexts:
    - name: webhook
      context:
        cluster: aws-iam-authenticator
        user: apiserver
